# dev only, see http://localhost:8080/graphiql?path=/graphql
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB     # adjust as needed
      max-request-size: 20MB
      # file-size-threshold: 0    # write directly to disk if >0
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  elasticsearch:
    uris: http://localhost:9200
  datasource:
    url: jdbc:mysql://localhost:3306/demo1
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
