server:
  servlet:
    context-path: /api
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  graphql:
    graphiql:
      enabled: true # dev only, see http://localhost:8080/graphiql?path=/graphql
      path: /graphiql
  task:
    elasticsearch:
      uris: localhost:9200
      username: elastic
      password: MyStrongPass123!
    datasource:
      username: root
      password: secret
      url: jdbc:mysql://127.0.0.1:3306/demo1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        poolName: HikariPool-Task
